ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
ENV['VAGRANT_CWD'] = "$VAGRANT_HOME/$project"
ENV['VAGRANT_VAGRANTFILE'] = '$VAGRANT_HOME/$project/Vagrantfile'

# Vagrant configuration file for the entire cluster
Vagrant.configure("2") do |config|

  # Controller or orchestrator VM  
  config.vm.define "controller" do |controller|
      controller.vm.box = "generic/alpine38"
      controller.vm.hostname = "controller"
      controller.ssh.forward_agent = true
      controller.ssh.keep_alive = true
      controller.vm.network "private_network", ip: "192.168.56.7"
      controller.vm.network "forwarded_port", guest: 22, host: 2207, host_ip: "127.0.0.1"
      controller.vm.network "forwarded_port", guest: 8080, host: 8087, host_ip: "127.0.0.1"
      controller.vm.provider :virtualbox do |v|
      v.memory = 1024
      v.cpus   = 2
      v.name   = "controller"
      v.customize ["modifyvm", :id, "--groups", "/vagrant"]
      end 
  end

    # Node1
    config.vm.define "worker1" do |worker1|
      worker1.vm.box = "generic/alpine38"
      worker1.vm.hostname = "worker-1"
      worker1.ssh.forward_agent = true
      worker1.ssh.keep_alive = true
      worker1.vm.network "private_network", ip: "192.168.56.8"
      worker1.vm.network "forwarded_port", guest: 22, host: 2208, host_ip: "127.0.0.1"
      worker1.vm.network "forwarded_port", guest: 80, host: 8088, host_ip: "127.0.0.1"
          worker1.vm.provider :virtualbox do |v|
          v.memory = 512
          v.cpus   = 1
          v.name = "vm-worker-1"
          v.customize ["modifyvm", :id, "--groups", "/vagrant"]
      end
  end

  # Node2
  config.vm.define "worker2" do |worker2|
      worker2.vm.box = "generic/alpine38"
      worker2.vm.hostname = "worker-2"
      worker2.ssh.forward_agent = true
      worker2.ssh.keep_alive = true
      worker2.vm.network "private_network", ip: "192.168.56.9"
      worker2.vm.network "forwarded_port", guest: 22, host: 2209, host_ip: "127.0.0.1"
      worker2.vm.network "forwarded_port", guest: 80, host: 8089, host_ip: "127.0.0.1"
      worker2.vm.provider :virtualbox do |v|
          v.memory = 512
          v.cpus   = 1
          v.name = "vm-worker-2"
          v.customize ["modifyvm", :id, "--groups", "/vagrant"]
      end
  end

end 